### ISSUE TITLE
isValidSeed is not working correct

### ISSUE THREAD

**Issue by troggy** [Colu-platform/hdwallet#2]
I had hard times convincing Colu SDK to accept privateSeed generated from mnemonic (BIP39, implementation by Bitcore). It failed on `isValidSeed` step saying "privateSeed should be a 256 bits hex (64 chars), if you are using WIF, use privateSeedWIF instead.". If I comment out this check, everything works correct. 

Here is the code to test. It derives an address from mnemonic using Bitcore and then tries to do the same with Colu. Same addresses are expected to be derived.

```
var Colu = require('colu');
var bitcore = require('bitcore-lib');

var Mnemonic = require('bitcore-mnemonic');

var mnemonic = new Mnemonic('legal winner thank year wave sausage worth useful legal winner thank yellow');

// generate address from mnemonic
var hdPrivateKey = mnemonic.toHDPrivateKey();
var accountKey = hdPrivateKey.derive(44, true).derive(0, true).derive(0, true);
var addr = accountKey.derive(0).derive(0).privateKey.toAddress();
console.log(addr);

// try do the same with Colu
var seed = mnemonic.toSeed();
var seedHex = seed.toString('hex');

var settings = {
    apiKey: 'Your API key',
    network: 'mainnet',
    privateSeed: seedHex // <-- this is not going to work?!
}

var colu = new Colu(settings);
colu.on('connect', function () {
    console.log(colu.hdwallet.getAddress()); // <-- should be the same as addr
});
colu.init();
```

**Comment by tal-beja** [comment]
I just updated the hdwallet (ver 0.4.28), to be able to accept 128-256 bits seed.
In the near future we may add the 'mnemonic' seed option to create the wallet and to export it out.

**Comment by troggy** [comment]
Tal, my test code still doesn't work with the fix.
Seed hex value is 878386efb78845b3355bd15ea4d39ef97d179cb712b77d5c12b6be415fffeffe5f377ba02bf3f8544ab800b955e51fbff09828f682052a20faa6addbbddfb096

**Comment by tal-beja** [comment]
This seed is 512 bits of length.
The maximum length size for a seed in our HDWallet is 256 bits for a reason, to export the seed to a WIF format we convert it to a private key which can only hold 256 bits of data.
The mnemonic module that you used creates only 512 bits seeds, while this one: https://www.npmjs.com/package/mnemonic creates a 128 bits seed.
